name: Android CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 17
          distribution: corretto

      # Grant execute permission for Gradle
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      # Build APK
      - name: Build with Gradle
        run: ./gradlew build

      # Run unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report

      # Upload APK
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: DPP-Viewer.apk
          path: app/build/outputs/apk/debug/app-debug.apk
